# -*- fill-column: 1000 -*-
kind: pipeline
name: build x86_64

volumes:
- name: debian-package-cache
  host:
    path: /var/cache/debian-package-cache

trigger:
  event:
    exclude:
    - tag

steps:
- name: download mastodon-cpp
  image: plugins/download
  settings:
    source: https://schlomp.space/tastytea/mastodon-cpp/releases/download/0.111.4/libmastodon-cpp_0.111.4-0_buster_amd64.deb
    destination: mastodon-cpp.deb

- name: gcc8
  image: debian:buster-slim
  pull: always
  environment:
    CXX: g++-8
    CXXFLAGS: -pipe -O2
    LANG: C.utf8
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - alias apt-get='rm -f /var/cache/apt/archives/lock && apt-get'
  - apt-get update -q
  - echo "deb https://packagecloud.io/mrtazz/restclient-cpp/debian/ buster main" > /etc/apt/sources.list.d/restclient-cpp.list
  - apt-get install -qy debian-archive-keyring curl gnupg apt-transport-https
  - curl -L https://packagecloud.io/mrtazz/restclient-cpp/gpgkey | apt-key add -
  - apt-get update -q
  - apt-get install -qy build-essential cmake asciidoc
  - apt-get install -qy libboost-filesystem-dev libboost-log-dev libjsoncpp-dev catch libcurl4-openssl-dev restclient-cpp libpoco-dev
  - apt-get -qy install ./mastodon-cpp.deb
  - rm -rf build && mkdir -p build && cd build
  - cmake ..
  - make VERBOSE=1
  - make install DESTDIR=install
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: notify
  image: drillster/drone-email
  pull: always
  settings:
    host: cryptoparty-celle.de
    from: drone@tzend.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
  when:
    status: [ changed, failure ]
