# -*- fill-column: 1000 -*-
kind: pipeline
name: build x86_64

volumes:
- name: debian-package-cache
  host:
    path: /var/cache/debian-package-cache

trigger:
  event:
    exclude:
    - tag

steps:
- name: download mastodonpp for buster
  image: plugins/download
  settings:
    source: https://schlomp.space/tastytea/mastodonpp/releases/download/0.5.7/libmastodonpp_0.5.7-0_amd64_buster.deb
    destination: mastodonpp_buster.deb

- name: download mastodonpp for bionic
  image: plugins/download
  settings:
    source: https://schlomp.space/tastytea/mastodonpp/releases/download/0.5.7/libmastodonpp_0.5.7-0_amd64_bionic.deb
    destination: mastodonpp_bionic.deb

- name: GCC 8 on Debian buster
  image: debian:buster-slim
  pull: always
  environment:
    CXX: g++-8
    CXXFLAGS: -pipe -O2
    DEBIAN_FRONTEND: noninteractive
    LANG: C.utf8
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - alias apt-get='rm -f /var/cache/apt/archives/lock && apt-get'
  - apt-get update -q
  - apt-get install -qq build-essential cmake pkg-config asciidoc
  - apt-get install -qq libboost-filesystem-dev libboost-log-dev libboost-regex-dev libjsoncpp-dev catch libcurl4-openssl-dev
  - apt-get -qq install ./mastodonpp_buster.deb
  - rm -rf build && mkdir -p build && cd build
  - cmake ..
  - make VERBOSE=1
  - make install DESTDIR=install
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: GCC 7 on Ubuntu bionic
  image: ubuntu:bionic
  pull: always
  environment:
    CXX: g++-7
    CXXFLAGS: -pipe -O2
    DEBIAN_FRONTEND: noninteractive
    LANG: C.utf8
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - alias apt-get='rm -f /var/cache/apt/archives/lock && apt-get'
  - apt-get update -q
  - apt-get install -qq build-essential cmake pkg-config asciidoc
  - apt-get install -qq libboost-filesystem-dev libboost-log-dev libboost-regex-dev libjsoncpp-dev catch libcurl4-openssl-dev
  - apt-get -qq install ./mastodonpp_bionic.deb
  - rm -rf build && mkdir -p build && cd build
  - cmake ..
  - make VERBOSE=1
  - make install DESTDIR=install
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: notify
  image: drillster/drone-email
  pull: always
  settings:
    host: mail.tzend.de
    from: drone@tzend.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
  when:
    status: [ changed, failure ]
