pipeline:
  download:
    image: plugins/download
    pull: true
    source: https://schlomp.space/attachments/713cd43b-8208-4e37-9fad-740daf7bdfa9
    destination: mastodon-cpp.deb
  gcc8:
    image: gcc:8
    pull: true
    commands:
      - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - apt-get update -q
      - apt-get install -qy cmake libcurl4-openssl-dev libjsoncpp-dev libboost-all-dev
      - apt-get install -qy -t sid libcurlpp-dev
      - dpkg -i mastodon-cpp.deb
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
  gcc7:
    image: gcc:7
    pull: true
    commands:
      - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - apt-get update -q
      - apt-get install -qy cmake libcurl4-openssl-dev libjsoncpp-dev libboost-all-dev
      - apt-get install -qy -t sid libcurlpp-dev
      - dpkg -i mastodon-cpp.deb
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
  notify:
    image: drillster/drone-email
    pull: true
    host: cryptoparty-celle.de
    secrets: [ email_username, email_password ]
    from: drone@tzend.de
    when:
      status: [ changed, failure ]
